### ISSUE TITLE
Iron Nugget issue

### ISSUE THREAD

**Issue by Wolf68k** [MJRLegends/Space-Astronomy-2-Feedback-#234] opened 2018-02-19 18:22 UTC
### ---Issue Report---
**(PLEASE DONT DELETE THIS TEMPLATE, YOUR ISSUE WILL BE IGNORED AND CLOSED IF YOU DO.)**

**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]

### Description of Issue
NeoTech Iron Nuggets are still useless. Can't be used for any crafting recipe even though when you look at the uses for them they show recipes but those recipes show the Backpart Iron Nugget. 
Also there are still ways to get NeoTech Iron Nuggets; Actually Additions Crusher crushing Railcraft Poor Iron Ore, Tinker I/O Smart Output with a nugget cast, Extra Utilities 2 Furnace with Railcraft Poor Iron Ore, Tinkers' Construct Smeltry with a nuggest cast, NeoTech Solidifier set to nugget mode, EnderIO Alloy Smelter with Railcraft Poor Iron Ore.

### Steps to Reproduce Issue
1. Look at the uses for Railcraft Poor Iron Ore.
2. Once you have a NeoTech Iron Nuggest look at the recipes and uses for it.

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
> *How do i locate a crash log on Minecraft on Curse/Twitch? see* https://gyazo.com/3c616a7dfcbe69033ea210805b093f82

**Screenshots (if applicable):** 

**Version of Mod Pack using (PLEASE DONT USE 'Latest' OR 'Newest'):** [VERSION]
1.4.2

**Where did this bug happen:** [Single Player or Server]
Single player but I would guess the same result would happen on a server

### Additional Information
Suggestion: Either disable the generation of Railcraft Poor Ores since that seems to be the problem or try to use MineTweaker to fix the problem some how. Personally I don't seen much point of the Railcraft Poor Ores so removing it might be the best solution.

**Comment by Wolf68k** [comment] 2018-02-19 22:30
So after looking into this further I've discovered something.
If try to look up the uses for the Backport Iron Nugget the only thing that shows up is making an iron ingot and putting them in the Tinkers' Smeltery. But looking at the NeoTech Iron Nugget you find a lot of things but they now all require the Backport Iron Nugget and are shown that way.
My suggestion is flip what you did in MineTweaker. Let NeoTech handle the iron nugget and remove the Backport recipes.
I did a test which was to remove all of what you had in the MineTweaker script that removed NeoTech and everything seems to make more logical sense with it as normal.

Still investigating.

**Comment by MJRLegends** [comment] 2018-02-19 22:31
Thanks i will take a look later

**Comment by MJRLegends** [comment] 2018-02-23 21:53
I will take a look for the next mod pack upload might be a few weeks though sorry for any pain caused by this issue :D

**Comment by Wolf68k** [comment] 2018-02-24 22:37
Last I've done to fix this. I removed all of the tweaks you had for both Backport (but for mods.tconstruct.Smeltery.addMelting(<liquid:iron> * 16, <backport:iron_nugget>, 345); I haven't gotten around to messing with it) and Neotech for the iron nugget. Then added in recipes.remove(<backport:iron_nugget>); and this seems to be ok so far. Neotech handles the iron nuggets.

I wouldn't suggest doing quite that, because the removals included the ore dict stuff. So those with the Backport nuggets now wouldn't be able to use them with anything. However, I think, going forward things should work themselves out.

Side note: It took me a little bit figure out why the nugget wasn't showing up in JEI. I didn't know JEI had a itemBlacklist.cfg file to hide things. (or I knew and I forget) So if you do go with the NeoTech nugget don't forget about this part.

**Comment by MJRLegends** [comment] 2018-02-25 23:48
Fixed in the next version

**Comment by MJRLegends** [comment] 2018-02-26 00:53
Version has been uploaded, Will be showing once its been approved on curseforge

**Closed by MJRLegends** 2018-02-26 00:53 UTC
Labels: bug, conflict bug, fixed in the next version
