### ISSUE TITLE
Most Open modular turrets not doing damage. 

### ISSUE THREAD

**Issue by Rocker-Fox** [MJRLegends/Space-Astronomy-2-Feedback-#131] opened 2017-09-22 07:38 UTC
### ---Issue Report---
**Have you checked Open/Closed Issues?** Yes. 1 Closed issue but the bug is either different or still remains. 

### -Description of Issue:
Most of the modular turrets from the open modular turrets pack do not do any damage to mobs or players. When firing they will show the projectile hitting the mob, it will show a damage animation (red flash) but the health bar will not be effected. 

There were only 2 exceptions to this being the Tier 2 incendiary turret and the tier 5 laser turret. I believe part of this is the different way that these 2 turrets apply damage. The teleport turret also works but does not apply direct damage so it's works as intended. 

### - Steps to Reproduce Issue:
1.  Open Creative game in single or multiplayer
2. Set up modular turrets base and turret, connect with power,, load with ammo, add any addons to check. 
3. Observe mob getting hit by turret
4. Check health bar and notice that the mob is not losing any hitpoints to the turret. 

**Version of Mod Pack using:** V1.3.0

**Where did this bug happen:**
Single and multiplayer

### -Additional Information:

**Including a link to a youtube video showing the bug in action:**
https://youtu.be/IEU-hPEx6SQ

**Comment by MJRLegends** [comment] 2017-09-27 00:20
Thanks for reporting this, i can confirm i can reproduce it so i've reported it to the devs https://github.com/OpenModularTurretsTeam/OpenModularTurrets/issues/383

**Comment by Keridos** [comment] 2017-09-27 14:57
Can you reproduce that with OMT installed only? Cannot reproduce that in my dev env.

**Comment by MJRLegends** [comment] 2017-09-28 00:04
@Keridos See my recent message on the issue ticket on your issue tracker for this test results

**Comment by MJRLegends** [comment] 2017-09-28 01:30
@Rocker-Fox Solution: Remove Vanilla Tools mod :D It will be fixed fully in the next update that is out in the next 24 hours

**Closed** 2017-09-29 04:05 UTC
Labels: bug, fix provided in issue, fixed in the next version
